### ISSUE TITLE
Clicks onto the dialog close it

### ISSUE THREAD

**Issue by fisherds** [rockwotj/FirebasePasswordKeeperiOS#1]
When creating or editing a password, clicking in the white area of the dialog closes the dialog.  The dialog should only close if the click is entirely outside the white area or a user hits cancel.

**Comment by rockwotj** [comment]
Ah, hopefully I can fix this without submitting a PR to the library that I used.

**Comment by rockwotj** [comment]
See https://github.com/tskulbru/NBMaterialDialogIOS/issues/3
