### ISSUE TITLE
swipe to delete

### ISSUE THREAD

**Issue by fisherds** [rockwotj/FirebasePasswordKeeperiOS#2]
Optional feature that could potentially be added if the framework allows it

**Comment by rockwotj** [comment]
Possible, but I think your request for webview signin for rosefire is going to take priority. Feel free to submit a PR :smile: 

Besides, most libraries I know want a custom cell and we already have one I spend too much time working on. So I'm good with the button. Feel free to let this feature be the thing to make it yours :smile:

**Comment by fisherds** [comment]
Sounds good.  I honestly was just mentioning it if it was a one liner provided by the framework. :)
