### ISSUE TITLE
Can't run on an actual device

### ISSUE THREAD

**Issue by fisherds** [rockwotj/FirebasePasswordKeeperiOS#4]
When trying to run the program on my phone I get this error...

/Pods/GoogleUtilities/Libraries/libGTM_NSData+zlib.a (GTMNSData+zlib.o) does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64

![enable_bitcode](https://cloud.githubusercontent.com/assets/295078/13613808/9bf375d4-e53b-11e5-8ed6-83417430f5f7.jpg)

**Comment by rockwotj** [comment]
Just had to disable bitcode.
