### ISSUE TITLE
Creating an Email/password account from within the app

### ISSUE THREAD

**Issue by fisherds** [rockwotj/FirebasePasswordKeeperiOS#8]
Need some mechanism to create an account (Email/Password Login) from within the app.  I assume that it is currently only this email/password account...

Email account is: test@example.com
Password is: abc123

**Comment by rockwotj** [comment]
Eventually the idea is to do this from the web client. If we have that available, would you still want to have it in-app?

**Comment by fisherds** [comment]
I would prefer it in-app, but it's a low priority.  A real company trying to sell an app would have make the app a 1 stop shop in order to meet user's expectations, but since it's a demo app we could do web only.  I **prefer** trying to make apps realistic when possible (unlike the Angular 2 Tour of Heros), but when the code get pretty tedious and obscures the actual learning objectives, then I begin to sing a different tune. :)

I almost wonder if the login flow should be two screens or a screen plus a dialog anyway.  For example it's weird to have the same text boxes for Email password and Rosefire to me.  I think I'd vote for the page to just have buttons, then all buttons launch some dialog (or webview in the case of Google).  Buttons might be:

Login with a Rose-Hulman account
Login with an existing email account
Create a new email account
Login with Google

Then each button launches a dialog with the appropriate words.  (if this happens make Rosefire say **username** instead of **email** btw)

**Comment by rockwotj** [comment]
Making a new view controller for creating an account. As for the same text boxes for both, this will change when we move to the webview signin.
